package com.parking.common.exception;

public enum ErrorCode {

    EMAIL_ALREADY_REGISTERED("EMAIL_ALREADY_REGISTERED"),
    MOBILE_ALREADY_REGISTERED("MOBILE_ALREADY_REGISTERED"),
    USER_REGISTERED("USER_REGISTERED"),
    VALIDATION_FAILED("VALIDATION_FAILED"),
	VEHICLE_REGISTERED("VEHICLE REGISTERED"),
	VEHICLE_ALREADY_REGISTERED("VEHICLE ALREADY REGISTERED"), 
	USER_NOT_FOUND("USER NOT FOUND"),
	PARKING_SPOT_ALREADY_REGISTERED("PARKING_SPOT_ALREADY_REGISTERED"),
	PARKING_SPOT_REGISTERED("PARKING_SPOT_REGISTERED"),
	VEHICLE_NOT_FOUND("VEHICLE NOT FOUND"),
	PARKING_SPOT_NOT_AVAILABLE("PARKING SPOT NOT AVAILABLE"), 
	VEHICLE_ALREADY_PARKED("VEHICLE_ALREADY_PARKED"),
	PARKING_SESSION_NOT_FOUND("PARKING_SESSION_NOT_FOUND"),
	PARKING_SESSION_ALREADY_COMPLETED("PARKING_SESSION_ALREADY_COMPLETED"),
	PARKING_RATE_NOT_FOUND("PARKING_RATE_NOT_FOUND");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
